Feature: Loggedinuser

Scenario: Perform all the action of the Logged in User
When I visit home page
Then I follow "Log in"
And I fill in "session_email" with "chef-1@example.com"
And I fill in "session_password" with "testpassword"
And I press "Log in"
Then I should see "You have successfully logged in"
And I should see "Chef chef 1's profile"
Then I follow "Recipes"
And I follow "Create a new Recipe"
Then I should see "Create a new recipe"
When I fill in "recipe_name" with "My Master Recipe"
And I fill in "recipe_description" with "Coming up Soon!"
And I press "Create Recipe"
Then I should see "Recipe was created successfully!"
And I should see "Edit this recipe"
And I should see "Delete this recipe"
When I follow "Edit this recipe"
Then I should see "Edit an existing recipe"
And I fill in "recipe_description" with "The Recipe will be shortly updated"
And I press "Update Recipe"
Then I should see "Recipe was updated successfully!"
When I follow "Chef 1's Profile"
And I follow "View your profile"
Then I should see "Chef chef 1's profile"
When I follow "Chef 1's Profile"
And I follow "Edit your profile"
Then I should see "Edit your profile"
And I fill in "chef_chefname" with "AdminChef"
And I press "Update my account"
Then I should see "Your account was updated successfully"
When I follow "Admin"
And I follow "Logout"
Then I should see "You have logged out"